### ISSUE TITLE
:each loop example

### ISSUE THREAD

**Issue by balaramadurai** [juanjosegarciaripoll/org-thtml#2]
Hello @juanjosegarciaripoll, 
  Thank you so much for your work on this wonderful templating system. It is so close to what I want. 

I have been able to replicate my website at https://balaramadurai.net (which is currently using org-mode and ox-hugo) using your template system.

I am stuck at two places.

1. How do I extract the latest posts (latest 4) like I can do with hugo's theme?
2. How do I use yaml like data formatting in org-mode like can be done with hugo? (hugo can read from set of yaml data to populate a html template) How do I do that with your template system?

Will `:each` help? In that case, can you please give some working examples of this looping system?

Thanks again for your work with this template system. It rocks!
Bala

**Comment by juanjosegarciaripoll** [comment]
Note that your problems are not "issues", but requests of features that were not covered in the previous version.

First, :each does nothing fancy, it just iterates over a lisp list. The problem you have is more complex: you first need to retrieve a list of posts, sort it and select a few of them. This is implemented in the new code I have uploaded (see "Bonus: Parse projects").

As for yaml files, I do not know how they work iand have never used them, hence it has not been implemented. You're welcome to contribute them, though. Or if you have a pressing need, submit it as a feature request, not an issue, and maybe someone will implement them.
